spring:
  profiles:
    active:
      - dev

---
spring:
  profiles: dev
  application:
      name: spring-cloud-config-devs

---
spring:
  profiles: test
  application:
      name: spring-cloud-config-test

server:
  port: 3344
